export const REVENUE_CHALLENGE_FORM_URL = "REPLACE_WITH_GOOGLE_FORM_URL";
export const BUILDERS_CHALLENGE_FORM_URL = "REPLACE_WITH_GOOGLE_FORM_URL";
export const CHALLENGE_CONTACT_EMAIL = "build@spiritualdata.org";
